name: continuous-integration

env:
  JAVA_OPTS: "-Dsbt.log.noformat=true"

defaults:
  run:
    shell: bash
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        scala: [2.12.12]
        java: ['1.8', '1.11']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: echo java version
        run: java -Xmx32m -version
      - name: echo javac version
        run: javac -J-Xmx32m -version
      - name: test
        run: ${{ format('sbt ++{0} clean test', matrix.scala) }}